#### Loan_Status Classification 

1) Read the 'loan_data.csv' dataset<br>
2) Remove/handle null values if any<br>
3) Select 'Loan_Status' column a s dependent feature and the remaining columns (or select appropriate features from the remaining features) as independent 
features, split the data into training and test data with test data size as 25%<br>
4) Apply the following models on training data and generate the prediction on test data.<br>
a) Decision Tree<br>
b) Random Forest<br>
c) SVM with linear kernel<br>
d) Gaussian NB<br>
e) KNN<br>
5) Generate confusion matrix and classification report for each and every algo used in Q4)<br>
6) Conclude the model with the best accuracy score amongst others

#### Optional
7)Apply the following models on training data and generate the prediction on test data.
Generate confusion matrix and classification report for them as well <br>
a) AdaBoost<br>
b) XGBoost<br>

8) Create a Neural Network model to implement this classification task. Genarte the predictions. Generate confusion matrix and classification report for them as well.

In [162]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [163]:
df=pd.read_csv('D:\PYTHON ALL/loan_data.csv')

In [164]:
df.head(5)

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [165]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [166]:
df['Gender'].value_counts()

Male      489
Female    112
Name: Gender, dtype: int64

In [167]:
df['Gender'].fillna(0,inplace=True)

In [168]:
df['Gender'] = df['Gender'].replace({'Male':1,'Female':0})
df.head(10)

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0  LP001002       1      No          0      Graduate            No   
1  LP001003       1     Yes          1      Graduate            No   
2  LP001005       1     Yes          0      Graduate           Yes   
3  LP001006       1     Yes          0  Not Graduate            No   
4  LP001008       1      No          0      Graduate            No   
5  LP001011       1     Yes          2      Graduate           Yes   
6  LP001013       1     Yes          0  Not Graduate            No   
7  LP001014       1     Yes         3+      Graduate            No   
8  LP001018       1     Yes          2      Graduate            No   
9  LP001020       1     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [169]:
df['Married'] = df['Married'].replace({'Yes':1,'No':0})
df['Married'].fillna(0,inplace=True)

In [170]:
df['Education'] = df['Education'].replace({'Graduate':1,'Not Graduate':0})
df['Self_Employed'] = df['Self_Employed'].replace({'Yes':1,'No':0})
df['Property_Area'] = df['Property_Area'].replace({'Urban':1,'Rural':2,'Semiurban':3})
df['Loan_Status'] = df['Loan_Status'].replace({'Y':1,'N':0})

In [171]:
df['Dependents'].fillna(0,inplace=True)
df['Self_Employed'].fillna(0,inplace=True)
df['LoanAmount'].fillna(0,inplace=True)
df['Loan_Amount_Term'].fillna(0,inplace=True)
df['Credit_History'].fillna(0,inplace=True)

In [172]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [173]:
df['Dependents'] = df['Dependents'].replace({'3+':0})

In [174]:
df.head(10)

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0  LP001002       1      0.0          0          1            0.0   
1  LP001003       1      1.0          1          1            0.0   
2  LP001005       1      1.0          0          1            1.0   
3  LP001006       1      1.0          0          0            0.0   
4  LP001008       1      0.0          0          1            0.0   
5  LP001011       1      1.0          2          1            1.0   
6  LP001013       1      1.0          0          0            0.0   
7  LP001014       1      1.0          0          1            0.0   
8  LP001018       1      1.0          2          1            0.0   
9  LP001020       1      1.0          1          1            0.0   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         0.0             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History  Property_Area  Loan_Status  
0             1.0              1            1  
1             1.0              2            0  
2             1.0              1            1  
3             1.0              1            1  
4             1.0              1            1  
5             1.0              1            1  
6             1.0              1            1  
7             0.0              3            0  
8             1.0              1            1  
9             1.0              3            0

In [175]:
x=df.iloc[:,1:-1]
y=df.iloc[:,-1]

In [176]:
x

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
0         1      0.0          0          1            0.0             5849   
1         1      1.0          1          1            0.0             4583   
2         1      1.0          0          1            1.0             3000   
3         1      1.0          0          0            0.0             2583   
4         1      0.0          0          1            0.0             6000   
..      ...      ...        ...        ...            ...              ...   
609       0      0.0          0          1            0.0             2900   
610       1      1.0          0          1            0.0             4106   
611       1      1.0          1          1            0.0             8072   
612       1      1.0          2          1            0.0             7583   
613       0      0.0          0          1            1.0             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0         0.0             360.0             1.0   
1               1508.0       128.0             360.0             1.0   
2                  0.0        66.0             360.0             1.0   
3               2358.0       120.0             360.0             1.0   
4                  0.0       141.0             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0        71.0             360.0             1.0   
610                0.0        40.0             180.0             1.0   
611              240.0       253.0             360.0             1.0   
612                0.0       187.0             360.0             1.0   
613                0.0       133.0             360.0             0.0   

     Property_Area  
0                1  
1                2  
2                1  
3                1  
4                1  
..             ...  
609              2  
610              2  
611              1  
612              1  
613              3  

[614 rows x 11 columns]

In [177]:
y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int64

In [178]:
from sklearn.model_selection import train_test_split

In [179]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)

### DECISION TREE 

In [180]:
from sklearn.tree import DecisionTreeClassifier

In [181]:
dt=DecisionTreeClassifier()

In [182]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [239]:
print("Training Accuracy",dt.score(x_train,y_train))
print("Testing Accuracy",dt.score(x_test,y_test))

Training Accuracy 0.9173913043478261
Testing Accuracy 0.9285714285714286


In [183]:
print(dt.score(x_test,y_test))

0.6818181818181818


In [184]:
dt_pred=dt.predict(x_test)

In [185]:
dt_pred[:10]

array([0, 1, 1, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [186]:
from sklearn.metrics import confusion_matrix, classification_report

In [187]:
print(confusion_matrix(y_test,dt_pred))

[[26 17]
 [32 79]]


In [188]:
print(classification_report(y_test,dt_pred))

              precision    recall  f1-score   support

           0       0.45      0.60      0.51        43
           1       0.82      0.71      0.76       111

    accuracy                           0.68       154
   macro avg       0.64      0.66      0.64       154
weighted avg       0.72      0.68      0.69       154



### RANDOM FOREST

In [189]:
from sklearn.ensemble import RandomForestClassifier

In [190]:
rf=RandomForestClassifier()

In [191]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [240]:
print("Training Accuracy",rf.score(x_train,y_train))
print("Testing Accuracy",rf.score(x_test,y_test))

Training Accuracy 0.941304347826087
Testing Accuracy 0.9545454545454546


In [192]:
print(rf.score(x_test,y_test))

0.7792207792207793


In [193]:
rf_pred=rf.predict(x_test)

In [194]:
rf_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [195]:
from sklearn.metrics import confusion_matrix, classification_report

In [196]:
print(confusion_matrix(y_test,rf_pred))

[[24 19]
 [15 96]]


In [197]:
print(classification_report(y_test,rf_pred))

              precision    recall  f1-score   support

           0       0.62      0.56      0.59        43
           1       0.83      0.86      0.85       111

    accuracy                           0.78       154
   macro avg       0.73      0.71      0.72       154
weighted avg       0.77      0.78      0.78       154



### SVM with linear kernel

In [198]:
from sklearn.svm import SVC,SVR 

In [199]:
kernel=['linear']

In [204]:
for i in kernel:
    model=SVC(kernel=i)
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)

In [205]:
print(f' in {i}  the accuracy score is {model.score(x_test,y_test)}')
print(f' in {i} the Confusion matrix is\n {confusion_matrix(y_pred,y_test)}')
print(f' in {i}  the Classification report is\n {classification_report(y_pred,y_test)}')

 in linear  the accuracy score is 0.7727272727272727
 in linear the Confusion matrix is
 [[20 12]
 [23 99]]
 in linear  the Classification report is
               precision    recall  f1-score   support

           0       0.47      0.62      0.53        32
           1       0.89      0.81      0.85       122

    accuracy                           0.77       154
   macro avg       0.68      0.72      0.69       154
weighted avg       0.80      0.77      0.78       154



### Gaussian NB

In [206]:
from sklearn.naive_bayes import GaussianNB

In [220]:
gnb=GaussianNB()

In [221]:
y_train

89     1
268    0
364    1
258    0
607    1
      ..
552    1
600    0
461    1
396    0
611    1
Name: Loan_Status, Length: 460, dtype: int64

In [223]:
gnb.fit(x_train, y_train)

GaussianNB()

In [224]:
print(gnb.score(x_test,y_test))

0.7142857142857143


In [225]:
gnb_pred=gnb.predict(x_test)

In [226]:
gnb_pred

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0],
      dtype=int64)

In [227]:
print(confusion_matrix(y_test,gnb_pred))

[[  8  30]
 [ 14 102]]


In [228]:
print(classification_report(y_test,gnb_pred))

              precision    recall  f1-score   support

           0       0.36      0.21      0.27        38
           1       0.77      0.88      0.82       116

    accuracy                           0.71       154
   macro avg       0.57      0.54      0.54       154
weighted avg       0.67      0.71      0.69       154



###  KNN

In [229]:
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor

In [231]:
knn=KNeighborsClassifier(n_neighbors=15)

In [232]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=15)

In [234]:
print("Training Accuracy",knn.score(x_train,y_train))
print("Testing Accuracy",knn.score(x_test,y_test))

Training Accuracy 0.7065217391304348
Testing Accuracy 0.6493506493506493


In [235]:
knn_y_pred=knn.predict(x_test)

In [236]:
knn_y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1],
      dtype=int64)

In [237]:
print(confusion_matrix(y_test,knn_y_pred))

[[ 4 34]
 [20 96]]


In [238]:
print(classification_report(y_test,knn_y_pred))

              precision    recall  f1-score   support

           0       0.17      0.11      0.13        38
           1       0.74      0.83      0.78       116

    accuracy                           0.65       154
   macro avg       0.45      0.47      0.45       154
weighted avg       0.60      0.65      0.62       154



###  Random forest is performing better then other algorithms

### Apply the following models on training data and generate the prediction on test data. Generate confusion matrix and classification report for them as well

### a) AdaBoost

In [247]:
from sklearn.ensemble import AdaBoostClassifier

In [249]:
ada=AdaBoostClassifier(n_estimators=15)

In [250]:
ada.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=15)

In [251]:
print("Training Accuracy",ada.score(x_train,y_train))
print("Testing Accuracy",ada.score(x_test,y_test))

Training Accuracy 0.7869565217391304
Testing Accuracy 0.7727272727272727


In [256]:
y_pred_ada = ada.predict(x_test)

In [257]:
y_pred_ada

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0],
      dtype=int64)

In [258]:
print(confusion_matrix(y_test,y_pred_ada))

[[ 19  19]
 [ 16 100]]


In [259]:
print(classification_report(y_test,y_pred_ada))

              precision    recall  f1-score   support

           0       0.54      0.50      0.52        38
           1       0.84      0.86      0.85       116

    accuracy                           0.77       154
   macro avg       0.69      0.68      0.69       154
weighted avg       0.77      0.77      0.77       154

